<?php
declare(strict_types=1);session_start();require __DIR__.'/bootstrap.php';
$pass=(string)($CFG['admin_password']??'');
if(isset($_POST['logout'])){session_destroy();header('Location: leads.php');exit;}
if(empty($_SESSION['rccg_admin'])){
  $err='';if($_SERVER['REQUEST_METHOD']==='POST'){if($pass!=='' && !hash_equals($pass,(string)($_POST['password']??''))){$err='Incorrect password.';}elseif($pass==='CHANGE-ME-NOW'||$pass===''){$err='Set a strong admin_password in rccg_fife_private/config.php first.';}else{$_SESSION['rccg_admin']=1;header('Location: leads.php');exit;}}
  ?><!doctype html><meta name="viewport" content="width=device-width"><title>RCCG Admin</title><style>body{font:16px system-ui;background:#f6f8fb;margin:0;padding:24px}.box{max-width:420px;margin:10vh auto;background:white;padding:24px;border-radius:18px;box-shadow:0 12px 34px #0001}input,button{width:100%;padding:12px;margin-top:10px;border-radius:10px;border:1px solid #d8e0ec}button{background:#0a4dbf;color:white;font-weight:800}</style><div class="box"><h1>RCCG Open Heavens Fife Admin</h1><p>Enter the admin password.</p><?php if($err):?><p style="color:#b42318"><?=htmlspecialchars($err)?></p><?php endif?><form method="post"><input type="password" name="password" required><button>Sign in</button></form></div><?php exit;
}
$csrf=$_SESSION['csrf']??=bin2hex(random_bytes(16));
function require_csrf():void{if(!hash_equals($_SESSION['csrf']??'',(string)($_POST['csrf']??'')))die('Invalid request.');}
$flash='';
if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['action'])){require_csrf();$a=$_POST['action'];
  if($a==='save_setting'){$DB->prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value')->execute([(string)$_POST['key'],(string)$_POST['value']]);$flash='Setting saved.';}
  elseif($a==='add_service'){$DB->prepare('INSERT INTO service_times(sort_order,day_label,time_label,service_name,note) VALUES(?,?,?,?,?)')->execute([(int)$_POST['sort_order'],trim((string)$_POST['day_label']),trim((string)$_POST['time_label']),trim((string)$_POST['service_name']),trim((string)$_POST['note'])]);$flash='Service time added.';}
  elseif($a==='save_recurring'){$stmt=$DB->prepare('UPDATE recurring_events SET title=?,schedule_label=?,weekdays=?,start_time=?,end_time=?,description=?,location_text=?,join_url=?,active=? WHERE id=?');$stmt->execute([trim((string)$_POST['title']),trim((string)$_POST['schedule_label']),trim((string)$_POST['weekdays']),trim((string)$_POST['start_time']),trim((string)$_POST['end_time']),trim((string)$_POST['description']),trim((string)$_POST['location_text']),trim((string)$_POST['join_url']),isset($_POST['active'])?1:0,(int)$_POST['id']]);$flash='Recurring schedule saved.';}
  elseif($a==='delete_service'){$DB->prepare('DELETE FROM service_times WHERE id=?')->execute([(int)$_POST['id']]);$flash='Service time deleted.';}
  elseif($a==='add_event'){$DB->prepare('INSERT INTO events(title,start_at,end_at,description,location,join_url,featured,active) VALUES(?,?,?,?,?,?,?,1)')->execute([trim((string)$_POST['title']),trim((string)$_POST['start_at']),trim((string)$_POST['end_at']),trim((string)$_POST['description']),trim((string)$_POST['location']),trim((string)$_POST['join_url']),isset($_POST['featured'])?1:0]);$flash='Event added.';}
  elseif($a==='delete_event'){$DB->prepare('DELETE FROM events WHERE id=?')->execute([(int)$_POST['id']]);$flash='Event deleted.';}
  elseif($a==='add_ref'){$DB->prepare('INSERT INTO donation_refs(label,reference_code,sort_order) VALUES(?,?,?)')->execute([trim((string)$_POST['label']),strtoupper(trim((string)$_POST['reference_code'])),(int)$_POST['sort_order']]);$flash='Donation reference added.';}
  elseif($a==='delete_ref'){$DB->prepare('DELETE FROM donation_refs WHERE id=?')->execute([(int)$_POST['id']]);$flash='Donation reference deleted.';}
  elseif($a==='delete_contact'){$DB->prepare('DELETE FROM contacts WHERE id=?')->execute([(int)$_POST['id']]);$flash='Message deleted.';}
  elseif($a==='delete_subscriber'){$DB->prepare('DELETE FROM subscribers WHERE id=?')->execute([(int)$_POST['id']]);$flash='Subscriber deleted.';}
  elseif($a==='delete_worshipper'){$DB->prepare('DELETE FROM first_time_worshippers WHERE id=?')->execute([(int)$_POST['id']]);$flash='First-time worshipper response deleted.';}
}
if(($_GET['export']??'')==='worshippers'){header('Content-Type:text/csv');header('Content-Disposition:attachment; filename="rccg-first-time-worshippers.csv"');$o=fopen('php://output','w');fputcsv($o,['created_at','name','email','phone','address','rating','may_contact','prayer_point','suggestion']);foreach($DB->query("SELECT created_at,name,email,phone,address,rating,may_contact,prayer_point,suggestion FROM first_time_worshippers ORDER BY id DESC") as $r){$r['may_contact']=$r['may_contact']?'Yes':'No';fputcsv($o,$r);}fclose($o);exit;}
if(($_GET['export']??'')==='verified'){header('Content-Type:text/csv');header('Content-Disposition:attachment; filename="rccg-verified-subscribers.csv"');$o=fopen('php://output','w');fputcsv($o,['email','verified_at','page']);foreach($DB->query("SELECT email,verified_at,page FROM subscribers WHERE verified_at IS NOT NULL ORDER BY verified_at DESC") as $r)fputcsv($o,$r);fclose($o);exit;}
$tab=$_GET['tab']??'dashboard';$settings=[];foreach($DB->query('SELECT key,value FROM settings') as $r)$settings[$r['key']]=$r['value'];
$hasRecurring=(bool)$DB->query("SELECT 1 FROM sqlite_master WHERE type='table' AND name='recurring_events'")->fetchColumn();
$DB->exec("CREATE TABLE IF NOT EXISTS first_time_worshippers (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT NOT NULL,phone TEXT NOT NULL,address TEXT NOT NULL DEFAULT '',prayer_point TEXT NOT NULL DEFAULT '',rating INTEGER NOT NULL,suggestion TEXT NOT NULL DEFAULT '',may_contact INTEGER NOT NULL DEFAULT 0,page TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,ip_hash TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'new')");
$counts=['subscribers'=>(int)$DB->query('SELECT COUNT(*) FROM subscribers')->fetchColumn(),'verified'=>(int)$DB->query('SELECT COUNT(*) FROM subscribers WHERE verified_at IS NOT NULL')->fetchColumn(),'messages'=>(int)$DB->query('SELECT COUNT(*) FROM contacts')->fetchColumn(),'first-time worshippers'=>(int)$DB->query('SELECT COUNT(*) FROM first_time_worshippers')->fetchColumn(),'events'=>(int)$DB->query('SELECT COUNT(*) FROM events WHERE active=1')->fetchColumn()];
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>RCCG Admin</title><style>body{font:15px/1.5 system-ui;background:#f6f8fb;color:#172033;margin:0}.wrap{max-width:1250px;margin:auto;padding:18px}.head{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.head h1{margin-right:auto}.nav{display:flex;gap:6px;overflow:auto;padding:8px 0 14px}.nav a{white-space:nowrap;text-decoration:none;padding:9px 12px;background:white;border:1px solid #dfe7f3;border-radius:10px}.nav a.on{background:#0a4dbf;color:white}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px}.card{background:white;border:1px solid #dfe7f3;border-radius:14px;padding:14px;margin:10px 0}.stat strong{font-size:28px;color:#062451}input,textarea,select,button{font:inherit;padding:10px;border:1px solid #cfd9e8;border-radius:9px;max-width:100%}input,textarea,select{width:100%}textarea{min-height:100px}button{font-weight:800;background:#0a4dbf;color:white;cursor:pointer}.danger{background:#fff;color:#b42318;border-color:#ffc9c4}table{width:100%;border-collapse:collapse;background:white}th,td{text-align:left;border-bottom:1px solid #e4e9f1;padding:9px;vertical-align:top}table{display:block;overflow:auto}.row{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px}.muted{color:#667085}.flash{background:#ecfdf3;color:#027a48;padding:10px;border-radius:10px}.tiny{font-size:12px}.badge{padding:3px 7px;border-radius:999px;background:#eef5ff;color:#0a4dbf}</style></head><body><div class="wrap"><div class="head"><h1>RCCG Open Heavens Fife Admin</h1><a href="../" target="_blank">Open WebApp ↗</a><form method="post"><button name="logout" value="1" class="danger">Sign out</button></form></div><?php if($flash):?><p class="flash"><?=htmlspecialchars($flash)?></p><?php endif?><nav class="nav"><?php foreach(['dashboard'=>'Dashboard','settings'=>'Church Info','services'=>'Service Times','events'=>"What's On",'lessons'=>'Discovery Class Teacher Manual','worshippers'=>'First-Time Worshippers','donations'=>'Donation','messages'=>'Messages','subscribers'=>'Subscribers'] as $k=>$v):?><a class="<?=$tab===$k?'on':''?>" href="?tab=<?=$k?>"><?=$v?></a><?php endforeach?></nav>
<?php if($tab==='dashboard'):?><div class="grid"><?php foreach($counts as $k=>$v):?><div class="card stat"><span class="muted"><?=htmlspecialchars(ucfirst($k))?></span><br><strong><?=$v?></strong></div><?php endforeach?></div><div class="card"><h2>Testing release</h2><p>Church content, service times, Zoom URL, events, Discovery Class lessons, donation references, subscribers and form submissions live in <code>rccg_fife_private/rccg.sqlite</code> outside <code>public_html</code>.</p></div>
<?php elseif($tab==='settings'):?><h2>Church Information & Links</h2><?php foreach(['phone','address','website','facebook','youtube','zoom_url','donation_sort_code','donation_account_number'] as $k):?><form class="card" method="post"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="action" value="save_setting"><input type="hidden" name="key" value="<?=$k?>"><label><strong><?=htmlspecialchars($k)?></strong></label><input name="value" value="<?=htmlspecialchars($settings[$k]??'')?>"><button>Save</button></form><?php endforeach?>
<?php elseif($tab==='services'):?><h2>Service Times</h2><p class="muted">These display rows are stored in the private SQLite database outside public_html.</p><form class="card" method="post"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="action" value="add_service"><div class="row"><input name="sort_order" type="number" value="100" placeholder="Sort"><input name="day_label" required placeholder="Day"><input name="time_label" required placeholder="Time"><input name="service_name" required placeholder="Service name"></div><textarea name="note" placeholder="Optional note"></textarea><button>Add service time</button></form><table><tr><th>Day</th><th>Time</th><th>Service</th><th>Note</th><th></th></tr><?php foreach($DB->query('SELECT * FROM service_times ORDER BY sort_order,id') as $r):?><tr><td><?=htmlspecialchars($r['day_label'])?></td><td><?=htmlspecialchars($r['time_label'])?></td><td><?=htmlspecialchars($r['service_name'])?></td><td><?=htmlspecialchars($r['note'])?></td><td><form method="post"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="action" value="delete_service"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="danger">Delete</button></form></td></tr><?php endforeach?></table>
<h2 style="margin-top:28px">Recurring What's On / Quick Access Schedule</h2><p class="muted">These recurring rules are also stored in the private SQLite database. Editing them does not require rebuilding public_html. Weekdays use 1=Monday through 7=Sunday. Leave Join URL blank when the rule already uses a private setting such as the church Zoom link.</p>
<?php if(!$hasRecurring):?><div class="card"><strong>Recurring schedule table is not installed yet.</strong><p>Run <code>upgrade_v6_3.php</code> in the private folder first.</p></div><?php else:?><?php foreach($DB->query('SELECT * FROM recurring_events ORDER BY sort_order,id') as $r):?><form class="card" method="post"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="action" value="save_recurring"><input type="hidden" name="id" value="<?=$r['id']?>"><h3><?=htmlspecialchars($r['title'])?></h3><div class="row"><label>Title<input name="title" value="<?=htmlspecialchars($r['title'])?>" required></label><label>Display schedule<input name="schedule_label" value="<?=htmlspecialchars($r['schedule_label'])?>"></label><label>Weekdays<input name="weekdays" value="<?=htmlspecialchars($r['weekdays'])?>"></label><label>Start<input name="start_time" type="time" value="<?=htmlspecialchars($r['start_time'])?>" required></label><label>End<input name="end_time" type="time" value="<?=htmlspecialchars($r['end_time'])?>"></label></div><label>Description<textarea name="description"><?=htmlspecialchars($r['description'])?></textarea></label><div class="row"><label>Literal location<input name="location_text" value="<?=htmlspecialchars($r['location_text'])?>" placeholder="Leave blank if location comes from Church Info"></label><label>Direct join URL<input name="join_url" value="<?=htmlspecialchars($r['join_url'])?>" placeholder="Leave blank if link comes from Church Info"></label></div><p class="tiny">Recurrence: <?=htmlspecialchars($r['recurrence_type'])?> · location setting: <?=htmlspecialchars($r['location_setting'])?> · join setting: <?=htmlspecialchars($r['join_setting'])?><?php if((int)$r['exception_nth']>0):?> · exception on occurrence <?=((int)$r['exception_nth'])?><?php endif?></p><label><input type="checkbox" name="active" style="width:auto" <?=$r['active']?'checked':''?>> Active</label> <button>Save recurring schedule</button></form><?php endforeach?><?php endif?>
<?php elseif($tab==='events'):?><h2>What's On</h2><form class="card" method="post"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="action" value="add_event"><div class="row"><input name="title" required placeholder="Event title"><input name="start_at" type="datetime-local" required><input name="end_at" type="datetime-local"><input name="location" placeholder="Location"></div><input name="join_url" placeholder="Join URL / Zoom URL"><textarea name="description" placeholder="Description"></textarea><label><input type="checkbox" name="featured" style="width:auto"> Featured</label><button>Add event</button></form><table><tr><th>Event</th><th>Start</th><th>Location</th><th></th></tr><?php foreach($DB->query('SELECT * FROM events ORDER BY start_at DESC') as $r):?><tr><td><?=$r['title']?></td><td><?=$r['start_at']?></td><td><?=$r['location']?></td><td><form method="post"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="action" value="delete_event"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="danger">Delete</button></form></td></tr><?php endforeach?></table>
<?php elseif($tab==='lessons'):?><h2>Discovery Class Teacher Manual</h2><div class="card"><p>The Discovery Class Teacher Manual is now loaded from authorised JSON files in <code>rccg_fife_private/discovery_class/2026-2027/teacher/</code>, outside <code>public_html</code>.</p><p>Only authorised Discovery Class Teacher Manual content is published in v6.</p><p>Use the private deployment package to update lesson files; no public rebuild is required for lesson-content changes.</p></div>
<?php elseif($tab==='worshippers'):?><div class="head"><h2>First-Time Worshippers</h2><a href="?tab=worshippers&export=worshippers">Export CSV</a></div><p class="muted">These responses are stored separately from the mailing list.</p><table><tr><th>Date</th><th>Name</th><th>Contact</th><th>Rating</th><th>May contact?</th><th>Address</th><th>Prayer Point</th><th>Suggestion</th><th></th></tr><?php foreach($DB->query('SELECT * FROM first_time_worshippers ORDER BY id DESC LIMIT 1000') as $r):?><tr><td class="tiny"><?=htmlspecialchars($r['created_at'])?></td><td><?=htmlspecialchars($r['name'])?></td><td><?=htmlspecialchars($r['email'])?><br><?=htmlspecialchars($r['phone'])?></td><td><?=str_repeat('★',max(0,min(5,(int)$r['rating'])))?> <span class="tiny">(<?=((int)$r['rating'])?>/5)</span></td><td><?=$r['may_contact']?'Yes':'No'?></td><td><?=htmlspecialchars($r['address'])?></td><td><?=nl2br(htmlspecialchars($r['prayer_point']))?></td><td><?=nl2br(htmlspecialchars($r['suggestion']))?></td><td><form method="post"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="action" value="delete_worshipper"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="danger">Delete</button></form></td></tr><?php endforeach?></table>
<?php elseif($tab==='donations'):?><h2>Donation References</h2><p>Bank details are edited under Church Info. References below can be changed without rebuilding the ZIP.</p><form class="card" method="post"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="action" value="add_ref"><div class="row"><input name="label" required placeholder="Label e.g. Tithe"><input name="reference_code" required placeholder="Reference e.g. TITHE"><input name="sort_order" type="number" value="100"></div><button>Add reference</button></form><table><tr><th>Label</th><th>Reference</th><th></th></tr><?php foreach($DB->query('SELECT * FROM donation_refs ORDER BY sort_order,id') as $r):?><tr><td><?=$r['label']?></td><td><code><?=$r['reference_code']?></code></td><td><form method="post"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="action" value="delete_ref"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="danger">Delete</button></form></td></tr><?php endforeach?></table>
<?php elseif($tab==='messages'):?><h2>Church Messages</h2><table><tr><th>Date</th><th>Type</th><th>Name</th><th>Email / Phone</th><th>Category</th><th>Message</th><th></th></tr><?php foreach($DB->query('SELECT * FROM contacts ORDER BY id DESC LIMIT 500') as $r):?><tr><td class="tiny"><?=$r['created_at']?></td><td><span class="badge"><?=$r['form_type']?></span></td><td><?=htmlspecialchars($r['name'])?></td><td><?=htmlspecialchars($r['email'])?><br><?=htmlspecialchars($r['phone'])?></td><td><?=htmlspecialchars($r['category'])?></td><td><?=nl2br(htmlspecialchars($r['message']))?></td><td><form method="post"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="action" value="delete_contact"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="danger">Delete</button></form></td></tr><?php endforeach?></table>
<?php elseif($tab==='subscribers'):?><div class="head"><h2>Subscribers</h2><a href="?tab=subscribers&export=verified">Export verified CSV</a></div><table><tr><th>Email</th><th>Status</th><th>Created</th><th>Source</th><th></th></tr><?php foreach($DB->query('SELECT * FROM subscribers ORDER BY id DESC LIMIT 1000') as $r):?><tr><td><?=htmlspecialchars($r['email'])?></td><td><span class="badge"><?=$r['verified_at']?'VERIFIED':'PENDING'?></span></td><td><?=$r['created_at']?></td><td class="tiny"><?=htmlspecialchars($r['page'])?></td><td><form method="post"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="action" value="delete_subscriber"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="danger">Delete</button></form></td></tr><?php endforeach?></table><?php endif?>
</div></body></html>
